// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhmoinfiwgecbfhnhuzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobW9pbmZpd2dlY2JmaG5odXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjUyODUsImV4cCI6MjA3MDg0MTI4NX0.s6pPy-c34qZhyThnovICf5nBt-aoilFLpZUhw41p0Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});